### PR TITLE
Add templates for module documents

### PR DESCRIPTION
**Pull request by manuelfuenmayor**
I've located the module templates inside a folder apart: `modules/`.
This folder contains both liquid files and adoc files as it was laid out in `templates_tbm/` from https://github.com/metanorma/iso-10303-srl/pull/44.

Is this setting reasonable?
If it is, I would have to move the existent resource templates to another folder: `resources/`.

### CODE REVIEW

**Comment by manuelfuenmayor** [comment]
This is a try to achieve with step 2 from https://github.com/metanorma/iso-10303-srl/pull/44#issue-2223274448.

**Comment by ronaldtse** [comment]
@manuelfuenmayor yes the structure is reasonable. However, some of the templates are identical to the original. Can we reuse them from the same path?

**Comment by manuelfuenmayor** [comment]
Sure, I was planning to create a common_files folder to that end.

**Comment by ronaldtse** [comment]
Sounds good. Then we should use a separate folder for “resource” templates.

**Comment by manuelfuenmayor** [comment]
@ronaldtse I've finished the update of the templates.
An update to the adoc files via `stepmod2mn` will also be necessary (i.e. step 3 from https://github.com/metanorma/iso-10303-srl/pull/44#issue-2223274448).
I've described these changes in https://github.com/metanorma/stepmod2mn/issues/159.

**Pull request merged**
